In [1]:
from quantum_graph import *
from my_graph import *

In [2]:
q = Qubits(3)
# construct quantum fourier transform for 3 qubits
q.X(2)
q.H(1)
q.CS(2,1)
q.CT(3,1)
q.H(2)
q.CS(3,2)
q.H(3)
q.swap(1,3)
a = q.matrix()

/Users/jeudi/QuantumCircuit/my_graph.py:91: RuntimeWarning: divide by zero encountered in log
  node.set_weight(qubit, -np.log(np.exp(-x)*a + np.exp(-y)*b))
/Users/jeudi/QuantumCircuit/my_graph.py:95: RuntimeWarning: divide by zero encountered in log
  node.set_weight(self.other(qubit), -np.log(np.exp(-x)*c + np.exp(-y)*d))
/Users/jeudi/QuantumCircuit/my_graph.py:95: RuntimeWarning: invalid value encountered in log
  node.set_weight(self.other(qubit), -np.log(np.exp(-x)*c + np.exp(-y)*d))


In [3]:
q = Qubits(3)
# construct quantum fourier transform for 3 qubits
print(q.matrix())
q.H(1)
print(q.matrix())

[[0. 1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]]
[[0.         0.70710678 1.         1.         0.70710678 0.
  0.        ]
 [0.         1.         1.         1.         0.         0.
  0.        ]
 [0.         0.70710678 1.         1.         0.70710678 0.
  0.        ]
 [0.         0.70710678 1.         1.         0.70710678 0.
  0.        ]
 [0.         0.70710678 0.         0.                nan 1.
  1.        ]
 [0.         0.70710678 0.         0.                nan 1.
  1.        ]
 [0.         0.70710678 0.         0.                nan 1.
  1.        ]]
